import {
  BarChart3,
  FileText,
  Home,
  Layers,
  List,
  Mail,
  NotepadText,
  PhoneCall,
  Users,
} from "lucide-react";

export const sidebarItems = [
  { id: 1, icon: Home },
  { id: 2, icon: Users },
  { id: 3, icon: Mail },
  { id: 4, icon: PhoneCall },
  { id: 5, icon: FileText },
  { id: 6, icon: Layers },
  { id: 7, icon: List },
  { id: 8, icon: BarChart3 },
  { id: 9, icon: NotepadText },
];

export const stats = [
  { id: 1, label: "New", value: "127", color: "text-gray-600" },
  { id: 2, label: "Contacted", value: "705k", color: "text-gray-600" },
  { id: 3, label: "Qualified", value: "249k", color: "text-gray-600" },
  { id: 4, label: "Working", value: "57k", color: "text-gray-600" },
  { id: 5, label: "Proposal Sent", value: "1.1k", color: "text-gray-600" },
  { id: 6, label: "Customer", value: "3.7k", color: "text-green-600" },
  { id: 7, label: "Lost Leads", value: "5.2k", color: "text-red-600" },
];

export const leads = [
  {
    id: "#3066",
    customer: "Olivia Rhye",
    company: "Empire Mark",
    email: "rhye@empiremark.io",
    phone: "+1 (218) 699-3149",
    value: "$1,821.02",
    tags: "Important",
    source: "Facebook",
    assigned: "/pic2.png",
    status: "Customer",
    created: "Just now",
  },
  {
    id: "#3065",
    customer: "Phoenix Baker",
    company: "Wit Ventures",
    email: "baker@witventures.com",
    phone: "+1 (326) 507-6709",
    value: "$8,398.70",
    tags: "Follow up",
    source: "Facebook",
    assigned: "/pic3.png",
    status: "Qualified",
    created: "44 mins ago",
  },
  {
    id: "#3064",
    customer: "Lana Steiner",
    company: "Factor Four",
    email: "steiner@factorfour.com",
    phone: "+1 (208) 608-6292",
    value: "$5,286.94",
    tags: "Review",
    source: "LinkedIn",
    assigned: "/pic4.png",
    status: "Working",
    created: "3 hr ago",
  },
  {
    id: "#3063",
    customer: "Demi Wilkinson",
    company: "Market Square",
    email: "wilkinson@marketsq.com",
    phone: "+1 (317) 234-8462",
    value: "$2,968.95",
    tags: "Follow up",
    source: "Dribbble",
    assigned: "/pic5.png",
    status: "Contacted",
    created: "7 hr ago",
  },
  {
    id: "#3062",
    customer: "Candice Wu",
    company: "Voice Firm",
    email: "candice@voicefirm.com",
    phone: "+1 (680) 539-0761",
    value: "$7,005.23",
    tags: "Review",
    source: "LinkedIn",
    assigned: "/pic6.png",
    status: "Qualified",
    created: "12 hr ago",
  },
  {
    id: "#3061",
    customer: "Natali Craig",
    company: "Maxus Media",
    email: "natali@maxusmedia.net",
    phone: "+1 (540) 683-1441",
    value: "$2,595.82",
    tags: "Review",
    source: "UpWork",
    assigned: "/pic7.png",
    status: "Proposal Sent",
    created: "Yesterday",
  },
];

export const leadsTableHeaders = [
  "",
  "Lead ID",
  "Customer",
  "Company",
  "Email",
  "Phone",
  "Value",
  "Tags",
  "Source",
  "Assigned",
  "Status",
  "Created",
  "",
];
